name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: asiflhr
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: Platane/snk@v3
        with:
          github_user_name: asiflhr
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          theme: dark
      - name: Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git add dist/github-contribution-grid-snake-dark.svg
          git commit -m "Update snake game"
          git push
